baseurl:        "/"
destination:    "./_site"
permalink:      "/:categories/:title/"
pygments:       true
exclude:        ["README.md", ".DS_Store", "CNAME", "LICENSE.txt", "node_modules", ".gitignore"]
include: 	['.well-known', '.well-known/keybase.txt']
owner-name:     "Daniel Ryan"
owner-page:     "http://dryan.com/"
owner-email:    "dryan@dryan.com"
name:           "CSS Smart Grid"
license:        "MIT License"
lsi:            false
port:           4000
markdown:       kramdown
